### ISSUE TITLE
CI is failing (timing out) on Julia nightly

### ISSUE THREAD

**Issue by DilumAluthge** [mcabbott/Tullio.jl#61]
On the most recent commit to `master` (`58c1fbb`), CI passed on Julia 1.4 and passed on Julia 1.5 but failed (timed out) on Julia nightly. Links to the logs:
- Julia 1.4.2 (passed in 1h 21m 42s): https://github.com/mcabbott/Tullio.jl/runs/1505716118
- Julia 1.5.3 (passed in 52m 41s ): https://github.com/mcabbott/Tullio.jl/runs/1505716124
- Julia nightly (failed - killed for timing out at 6h 0m 13s): https://github.com/mcabbott/Tullio.jl/runs/1505716131

GitHub Actions will kill a job if it runs for more than six hours.

We need to figure out how to make the CI jobs run for less than six hours.

Here is one option: we separate the test suite into "groups". E.g. if currently the test suite looks like this:
```julia
using Tullio
using Test

@test f() == "a"

@test g() == "b"

@test h() == "c"
```

We instead divide the test suite into three groups as such:
```julia
using Tullio
using Test

test_group = get(ENV, "TULLIO_TEST_GROUP", "all")

if test_group in ["all", "1"]
    @test f() == "a"
end

if test_group in ["all", "2"]
    @test g() == "b"
end

if test_group in ["all", "3"]
    @test h() == "c"
end
```

And then we set up the `matrix` in `.github/workflows/ci.yml` file as such:
```yaml
strategy:
  fail-fast: false
  matrix:
    JULIA_NUM_THREADS:
      - '1'
      - '6'
    TULLIO_TEST_GROUP:
      - '1'
      - '2'
      - '3'
    version:
      - '1.4'
      - '1' # automatically expands to the latest stable 1.x release of Julia
    os:
      - ubuntu-latest
    arch:
      - x64
```

@mcabbott @chriselrod Any thoughts?
